## DEEP LEARNING 
### Pytorch Basic

In [9]:
import torch 
torch.cuda.is_available()

False

Dataset with pytorch

In [10]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv('./Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [12]:
df.shape

(150, 6)

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(['Species'], axis=1).values
Y = le.fit_transform(df['Species'].values)

# Chia dữ liệu với text size = 20%
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
Y_train = torch.LongTensor(Y_train).reshape(-1, 1)
Y_test = torch.LongTensor(Y_test).reshape(-1, 1)

In [14]:
len(Y_train)

120

In [15]:
labels, counts = Y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


# Tính đạo hàm bằng pytorch
# cho y = 2x^4 + x^3 + 3x^2 + 5x + 1
# Tính y'

In [16]:
import torch

In [17]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [18]:
# Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [19]:
y.grad_fn

In [20]:
# Thực hiện lan truyền ngược và tính toán các gradient 
y.backward()

In [21]:
x.grad

tensor(93.)

### BTVN:
# Cho y = 5x^5 + 6x^3 + 3x + 1
# Cho biết độ dốc của đa thức trên ở điểm nào?

In [34]:
import torch

x = torch.tensor(1.0, requires_grad=True)
y = 5*x**5 + 6*x**3 + 3*x + 1
y.backward()

print("Giá trị x : ", x.item())
print("Độ dốc tại điểm đó là", x.grad.item())

Giá trị x :  1.0
Độ dốc tại điểm đó là 46.0


##### BTVN 2: Tạo một tensor ban đầu có giá trị là 2. Định nghĩa hàm số và tính gradient
            y = x ^ 3 + 2x ^ 2 + 5x + 1             

- Hãy tính dy/dx tại giá trị của x

- Dùng phương pháp Gradient Descent với Learning Rate Alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp 


In [35]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 2*x**2 + 5*x + 1
y.backward()

print("Giá trị x ban đầu : ", x.item())
print("Gradient dy/dx tại x : ", x.grad.item())

Giá trị x ban đầu :  2.0
Gradient dy/dx tại x :  25.0


In [36]:
learning_rate = 0.1
input_tensor = torch.tensor(2.0, requires_grad=True)

print("Biểu đồ giảm Gradient: ")
print("=" * 40)

for iteration in range(10):
    if input_tensor.grad is not None:
        input_tensor.grad.zero_()
    
    output = input_tensor**3 + 2*input_tensor**2 + 5*input_tensor + 1
    output.backward()
    
    with torch.no_grad():
        input_tensor -= learning_rate * input_tensor.grad
    
    print(f"Lần {iteration+1:2d}: giá trị x = {input_tensor.item():.6f}, đạo hàm = {input_tensor.grad.item():.6f}")

Biểu đồ giảm Gradient: 
Lần  1: giá trị x = -0.500000, đạo hàm = 25.000000
Lần  2: giá trị x = -0.875000, đạo hàm = 3.750000
Lần  3: giá trị x = -1.254688, đạo hàm = 3.796875
Lần  4: giá trị x = -1.725085, đạo hàm = 4.703972
Lần  5: giá trị x = -2.427826, đạo hàm = 7.027413
Lần  6: giá trị x = -3.724998, đạo hàm = 12.971715
Lần  7: giá trị x = -6.897680, đạo hàm = 31.726830
Lần  8: giá trị x = -18.912006, đạo hàm = 120.143257
Lần  9: giá trị x = -119.146408, đạo hàm = 1002.343933
Lần 10: giá trị x = -4330.747559, đạo hàm = 42116.011719


##### BTVN 3: Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm tính theo công thức: 
        
            y = 3x + 5 + noise             

**Ghi chú:** --> noise là một giá trị ngẫu nhiên nhỏ

1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad = True
2. Tính MSE
3. Tính Gradient
4. Cập nhật tham số w và b bằng Gradient Descent với learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình.

In [41]:
import torch

# Tạo x: số giờ học từ 1 đến 10
x = torch.rand(20, 1) * 9 + 1
print("Số giờ học (x) - 5 mẫu đầu:")
print(x[:5])

# Tạo noise nhỏ
noise = torch.randn(20, 1) * 1.0

# Tạo y theo công thức: y = 3x + 5 + noise
y = 3 * x + 5 + noise
print("\nĐiểm số (y) - 5 mẫu đầu:")
print(y[:5])

Số giờ học (x) - 5 mẫu đầu:
tensor([[5.5125],
        [3.8255],
        [5.1882],
        [2.4507],
        [2.4112]])

Điểm số (y) - 5 mẫu đầu:
tensor([[23.0179],
        [16.8215],
        [19.1404],
        [12.2357],
        [10.3331]])


In [43]:
# Tạo w và b ngẫu nhiên
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"w = {w.item():.4f}")
print(f"b = {b.item():.4f}")
print(f"\nMô hình ban đầu: y = {w.item():.4f} * x + {b.item():.4f}")
print("Mô hình thực tế: y = 3.0 * x + 5.0")

w = 0.4485
b = 0.0330

Mô hình ban đầu: y = 0.4485 * x + 0.0330
Mô hình thực tế: y = 3.0 * x + 5.0


In [44]:
# Tính dự đoán
y_pred = w * x + b

# Tính MSE loss
loss = torch.mean((y_pred - y) ** 2)

print("Ví dụ 3 mẫu đầu:")
for i in range(3):
    print(f"x={x[i].item():.1f} -> y_thực={y[i].item():.2f}, y_dự_đoán={y_pred[i].item():.2f}")

print(f"\nMSE Loss = {loss.item():.4f}")

Ví dụ 3 mẫu đầu:
x=5.5 -> y_thực=23.02, y_dự_đoán=2.51
x=3.8 -> y_thực=16.82, y_dự_đoán=1.75
x=5.2 -> y_thực=19.14, y_dự_đoán=2.36

MSE Loss = 319.3583


In [45]:
# Tính gradient
loss.backward()

print(f"Gradient của w: {w.grad.item():.4f}")
print(f"Gradient của b: {b.grad.item():.4f}")

# Giải thích đơn giản
if w.grad.item() > 0:
    print("-> w đang quá lớn, cần giảm w")
else:
    print("-> w đang quá nhỏ, cần tăng w")

Gradient của w: -183.1866
Gradient của b: -33.0951
-> w đang quá nhỏ, cần tăng w


In [46]:
# Learning rate
alpha = 0.01

# Lưu giá trị cũ
w_cu = w.item()
b_cu = b.item()

# Cập nhật
with torch.no_grad():
    w -= alpha * w.grad
    b -= alpha * b.grad

# Xóa gradient
w.grad.zero_()
b.grad.zero_()

print(f"Trước cập nhật: w={w_cu:.4f}, b={b_cu:.4f}")
print(f"Sau cập nhật:  w={w.item():.4f}, b={b.item():.4f}")
print(f"w thay đổi: {w.item() - w_cu:.4f}")
print(f"b thay đổi: {b.item() - b_cu:.4f}")

Trước cập nhật: w=0.4485, b=0.0330
Sau cập nhật:  w=2.2803, b=0.3640
w thay đổi: 1.8319
b thay đổi: 0.3310


In [47]:
# Khởi tạo lại tham số
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
alpha = 0.01

print(f"Bắt đầu: w={w.item():.4f}, b={b.item():.4f}")
print("\nTiến trình:")
print("-" * 50)

for i in range(100):
    # Tính dự đoán
    y_pred = w * x + b
    
    # Tính loss
    loss = torch.mean((y_pred - y) ** 2)
    
    # Tính gradient
    loss.backward()
    
    # Cập nhật
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    
    # Xóa gradient
    w.grad.zero_()
    b.grad.zero_()
    
    # In kết quả
    if (i + 1) % 20 == 0:
        print(f"Lần {i+1:3d}: Loss={loss.item():.4f}, w={w.item():.4f}, b={b.item():.4f}")

print("-" * 50)
print(f"\nKết quả cuối:")
print(f"w = {w.item():.4f} (gần 3.0)")
print(f"b = {b.item():.4f} (gần 5.0)")
print(f"Loss = {loss.item():.4f}")

# Kiểm tra
print(f"\nKiểm tra:")
x_test = 4.0
y_thuc = 3 * x_test + 5
y_du_doan = w.item() * x_test + b.item()
print(f"Với x={x_test}:")
print(f"  Thực tế: y = {y_thuc:.2f}")
print(f"  Dự đoán: y = {y_du_doan:.2f}")
print(f"  Sai số: {abs(y_thuc - y_du_doan):.2f}")

Bắt đầu: w=1.4503, b=-0.6936

Tiến trình:
--------------------------------------------------
Lần  20: Loss=5.1796, w=3.8672, b=0.1262
Lần  40: Loss=4.5059, w=3.8055, b=0.4866
Lần  60: Loss=3.9423, w=3.7490, b=0.8163
Lần  80: Loss=3.4708, w=3.6974, b=1.1179
Lần 100: Loss=3.0765, w=3.6501, b=1.3937
--------------------------------------------------

Kết quả cuối:
w = 3.6501 (gần 3.0)
b = 1.3937 (gần 5.0)
Loss = 3.0765

Kiểm tra:
Với x=4.0:
  Thực tế: y = 17.00
  Dự đoán: y = 15.99
  Sai số: 1.01


# ------------------------------------------------------------------------

In [22]:
# Pytorch uwith Tensor
import torch 
import numpy as np

In [23]:
torch.__version__

'2.9.1+cpu'

In [24]:
# Chuyển đổi mảng numpy sang tensor pytorch
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [25]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [26]:
print(x.dtype)

torch.int64


In [27]:
print(x.type())

torch.LongTensor


In [28]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [29]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [30]:
# Copy and sharing
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [31]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5])


In [32]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [33]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


##### BTVN 4: Giải thích 2 trường hợp ở trên

# Sự khác biệt này được giải thích như sau:

**1.** Nguyên nhân xuất phát từ phương pháp tạo tensor khác nhau trong PyTorch.

**2.** Khi sử dụng `torch.from_numpy()`, PyTorch tạo tensor bằng cách tham chiếu đến cùng một vùng bộ nhớ với mảng NumPy. Do đó, mọi thay đổi trên mảng NumPy sẽ ngay lập tức phản ánh trên tensor.

**3.** Ngược lại, với `torch.tensor()`, PyTorch tạo ra một tensor mới có bản sao độc lập của dữ liệu. Tensor này không chia sẻ bộ nhớ với mảng NumPy gốc, nên việc thay đổi mảng NumPy không ảnh hưởng đến tensor đã tạo.

##### BTVN 5: 
- Bạn giúp thầy tạo tensor với
- empty
- zeros
- ones
- random
- reshape với view và view as

In [ ]:
# 1. empty: tạo tensor với giá trị rỗng
print("\n1. torch.empty(2, 3):")
print(torch.empty(2, 3))


1. torch.empty(2, 3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [49]:
# 2. zeros: tạo tensor toàn số 0
print("\n2. torch.zeros(3, 2):")
print(torch.zeros(3, 2))


2. torch.zeros(3, 2):
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [50]:
# 4. random: tạo tensor số ngẫu nhiên
print("\n4. torch.rand(2, 3):")
print(torch.rand(2, 3))


4. torch.rand(2, 3):
tensor([[0.7610, 0.7628, 0.6870],
        [0.4121, 0.3676, 0.5535]])


In [51]:
# 5. reshape với view
tensor = torch.arange(6)
print(f"\n5.1 Tensor gốc: {tensor}")
print(f"view(2, 3):\n{tensor.view(2, 3)}")
print(f"view(3, 2):\n{tensor.view(3, 2)}")


5.1 Tensor gốc: tensor([0, 1, 2, 3, 4, 5])
view(2, 3):
tensor([[0, 1, 2],
        [3, 4, 5]])
view(3, 2):
tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [52]:
# 6. reshape với view_as
template = torch.zeros(2, 3)
print(f"\n5.2 Template: shape {template.shape}")
print(f"view_as(template):\n{tensor.view_as(template)}")


5.2 Template: shape torch.Size([2, 3])
view_as(template):
tensor([[0, 1, 2],
        [3, 4, 5]])
