# DEEP LEARNING 

## TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

# NUMBY

In [1]:
# NUMBY là thư viện kiểu list
# vì :
#+ numby nhanh 
#+ có nhiều hàm tích hợp dễ sử dụng cho AI 

# để sử dụng numpy thì : pip install numpy
import numpy as np

In [2]:
# thử tạo 1 list 
python_list = [1, 2, 3]
numpy_list = np.array(python_list)

type(numpy_list)  # sẽ trả về numpy.ndarray

numpy.ndarray

In [3]:
# list trong python có thể hỗ trợ nhiều loại trong list

my_list = [1, "chào",True , 2.0]

In [6]:
my_list = [1, 2, 3, 4.5]
np_list = np.array(my_list)
np_list 

array([1. , 2. , 3. , 4.5])

In [7]:
# Chuyển đổi dữ liệu thi sao ?

np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [11]:
# accesing và indexing 
x = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # x = np.array(range(1,9))

In [12]:
# lấy số 4 
x[3]

np.int64(4)

In [13]:
# lấy nhiều hơn 1 phần tử 
# công thức [start:end:step]
#lấy 1 2 3 
x[0:3]

array([1, 2, 3])

In [15]:
# lấy từ 3 - 8 theo 3 cách
x[2:8]
x[2:]
x[2:8:1]

array([3, 4, 5, 6, 7, 8])

In [16]:
# không đúng 
x[2:-1]

array([3, 4, 5, 6, 7])

In [18]:
# lấy số 3 số 5
x[2],x[4]

(np.int64(3), np.int64(5))

In [19]:
# đặt danh sách các index muốn truy cập
x[[2, 4]]

array([3, 5])

In [20]:
data = [[1, 2], [3, 4], [5, 6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# lấy số 2
np_list[0,1]

array([[1, 2]])

In [ ]:
# lấy 3 4 5 6 
np_list[1:, :]


array([[3, 4],
       [5, 6]])

In [30]:
# cách 2
np_list[[1,2], :]

array([[3, 4],
       [5, 6]])

In [29]:
# cách 3 
np_list[1:]

array([[3, 4],
       [5, 6]])

In [31]:
# cách 4 
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [41]:
# lấy 1, 3, 5 
np_list[:, 0]


array([1, 3, 5])

In [ ]:
# lấy 1 và 5 theo 2 cách
np_list[[0,2], 0]



array([1, 5])

In [47]:
np_list[[-1,0], 0]

array([5, 1])

In [48]:
np_list[0::2,0]

array([1, 5])

In [49]:
x = ([
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12],
  [13, 14, 15, 16]])

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
# lấy 2 6 10 14 
np_list[:,1]

array([ 2,  6, 10, 14])

In [51]:
#lấy 7 và 11
np_list[1:3,2]

array([ 7, 11])

In [ ]:
#lấy 7 và 11
np_list[[1,2],2]

In [ ]:
# lấy 4 7 10


array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [66]:
# lấy 16 15 14 13
np_list[3::3]



array([[13, 14, 15, 16]])

# BTVN 1
## Cho ma trận = [[99,99,99],
##                [99,99,99],
##                [99,99,99]]

### hãy tưởng tượng ô 99 trống 
### giả sử 1 là x 
### giả sử 0 là o

### lấy đầu vào từ phía X và phía O luân phiên 
### nếu đầu vào từ phía x là (0,0)

### ma trận sẽ trở thành 
## [[x,99,99],
##  [99,99,99],
##  [99,99,99]]

# nếu đầu vào từ phía O cũng là (0,0)
# thông báo nhập lại 
# nếu không điền vào ma trận 

# thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi.



In [ ]:
# BTVN 2
y = (
    [1,2,3],
    [4,5,6],
    [7,8,9]
)

# Lấy 4,5,6

# Lấy 2,5 
# Lấy 3,4
# Lấy 9,6,3

In [ ]:
# BTVN 3 

# Cho x = [1,2,3,4,5,6,7,8,9,10]

# 1. Xuất ra các giá trị chẵn sử dụng if
x = [1,2,3,4,5,6,7,8,9,10]
for i in x:
    if i % 2 == 0:
        print(i)
# 2. Xuất ra các giá trị chẵn sử dụng list comprehension
even_numbers = [i for i in x if i % 2 == 0]

In [67]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [69]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [70]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
idx = [True , True, True, False, True, True, True, False, True, False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [72]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# BTVN 4
# Tạo 1 mảng numpy có kích thước 150 x 5 . Giả sử mảng này chứa 150 mảng dữ liệu 
# của nhân viên bao gồm chiều cao , cân nặng , tuổi , lương và điểm trung bình
# Tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y

# Tách mảng x thành x_train và x_test với trong đó x_train chứa 70% dữ liệu và tách y thành y_train và y_test chứa 70% dữ liệu

# Tạo 10 tập dữ liệu x_train không chồng chéo nhau
  